"""
Mock per-account dataset for the Account Explorer.

50 accounts spanning all 5 waves, distributed across departments, roles,
platforms, and NHI types.  Structure mirrors what Agent 01 (Discovery),
Agent 03 (Permissions), Agent 04 (ETL), and Agent 12 (NHI Handler) produce.
"""

ACCOUNTS = [
    # ── Wave 1: Test/Dev (10 accounts) ──────────────────────────────
    {
        "id": "ACC-00001", "name": "dev-web-01", "userName": "svc-dev-web",
        "address": "dev-web01.lab.corp.net", "safeName": "DEV-WebServers",
        "platformId": "WinServerLocal", "secretType": "password",
        "department": "Engineering", "title": "DevOps Engineer", "role": "operator",
        "manager": "Sarah Chen", "employee_id": "EMP-10201",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 1, "wave_reason": "safe matches 'dev' pattern",
        "batch": "W1B0", "risk": "low", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 6, "has_sensitive_permissions": False,
        "dependencies": [], "last_accessed": "2026-02-28T14:30:00Z",
        "created_date": "2024-03-15T09:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "ViewAuditLog", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "AccessWithoutConfirmation"],
    },
    {
        "id": "ACC-00002", "name": "test-db-oracle-01", "userName": "ora_test_user",
        "address": "testdb01.lab.corp.net", "safeName": "TEST-Databases",
        "platformId": "Oracle", "secretType": "password",
        "department": "Engineering", "title": "DBA", "role": "operator",
        "manager": "Sarah Chen", "employee_id": "EMP-10202",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 1, "wave_reason": "safe matches 'test' pattern",
        "batch": "W1B0", "risk": "low", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 4, "has_sensitive_permissions": False,
        "dependencies": [], "last_accessed": "2026-03-01T08:15:00Z",
        "created_date": "2024-06-20T11:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers"],
    },
    {
        "id": "ACC-00003", "name": "sandbox-linux-01", "userName": "sandbox_admin",
        "address": "sandbox01.lab.corp.net", "safeName": "SANDBOX-Servers",
        "platformId": "UnixSSH", "secretType": "password",
        "department": "DevOps", "title": "Site Reliability Engineer", "role": "admin",
        "manager": "Marcus Rivera", "employee_id": "EMP-10315",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 1, "wave_reason": "safe matches 'sandbox' pattern",
        "batch": "W1B0", "risk": "low", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 12, "has_sensitive_permissions": True,
        "dependencies": [], "last_accessed": "2026-02-25T16:45:00Z",
        "created_date": "2024-01-10T08:30:00Z",
        "target_role_a": "Edit", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "AddAccounts", "UpdateAccountContent", "UpdateAccountProperties", "DeleteAccounts", "ViewAuditLog", "ManageSafe", "ManageSafeMembers", "InitiateCPMAccountManagementOperations"],
    },
    {
        "id": "ACC-00004", "name": "poc-azure-vm-01", "userName": "poc_azure_admin",
        "address": "pocvm01.eastus.cloudapp.azure.com", "safeName": "POC-Cloud",
        "platformId": "WinServerLocal", "secretType": "password",
        "department": "Engineering", "title": "Cloud Engineer", "role": "operator",
        "manager": "Sarah Chen", "employee_id": "EMP-10220",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 1, "wave_reason": "safe matches 'poc' pattern",
        "batch": "W1B0", "risk": "low", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 5, "has_sensitive_permissions": False,
        "dependencies": [], "last_accessed": "2026-02-20T10:00:00Z",
        "created_date": "2025-01-05T14:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "ViewAuditLog"],
    },
    {
        "id": "ACC-00005", "name": "demo-app-frontend", "userName": "demo_user",
        "address": "demo-app.lab.corp.net", "safeName": "DEMO-Applications",
        "platformId": "WinServerLocal", "secretType": "password",
        "department": "Engineering", "title": "App Developer", "role": "viewer",
        "manager": "Sarah Chen", "employee_id": "EMP-10225",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 1, "wave_reason": "safe matches 'demo' pattern",
        "batch": "W1B0", "risk": "low", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 3, "has_sensitive_permissions": False,
        "dependencies": [], "last_accessed": "2026-01-15T12:00:00Z",
        "created_date": "2025-03-01T09:00:00Z",
        "target_role_a": "List", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts"],
    },
    {
        "id": "ACC-00006", "name": "lab-mysql-test", "userName": "mysql_lab",
        "address": "labdb01.lab.corp.net", "safeName": "LAB-Databases",
        "platformId": "MySQL", "secretType": "password",
        "department": "Engineering", "title": "DBA", "role": "operator",
        "manager": "Sarah Chen", "employee_id": "EMP-10230",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 1, "wave_reason": "safe matches 'lab' pattern",
        "batch": "W1B0", "risk": "low", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 4, "has_sensitive_permissions": False,
        "dependencies": [], "last_accessed": "2026-02-10T09:30:00Z",
        "created_date": "2025-02-14T10:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers"],
    },
    {
        "id": "ACC-00007", "name": "dev-api-gateway", "userName": "dev_api_admin",
        "address": "dev-gw01.lab.corp.net", "safeName": "DEV-Infrastructure",
        "platformId": "UnixSSH", "secretType": "password",
        "department": "DevOps", "title": "DevOps Engineer", "role": "operator",
        "manager": "Marcus Rivera", "employee_id": "EMP-10316",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 1, "wave_reason": "safe matches 'dev' pattern",
        "batch": "W1B0", "risk": "low", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 7, "has_sensitive_permissions": False,
        "dependencies": [], "last_accessed": "2026-03-02T11:00:00Z",
        "created_date": "2024-09-01T08:00:00Z",
        "target_role_a": "Edit", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "AddAccounts", "UpdateAccountContent", "ViewAuditLog"],
    },
    {
        "id": "ACC-00008", "name": "test-mssql-staging", "userName": "mssql_test",
        "address": "testdb02.lab.corp.net", "safeName": "TEST-Databases",
        "platformId": "MSSql", "secretType": "password",
        "department": "IT Operations", "title": "System Admin", "role": "operator",
        "manager": "David Park", "employee_id": "EMP-10105",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 1, "wave_reason": "safe matches 'test' pattern",
        "batch": "W1B0", "risk": "low", "status": "in_progress",
        "pipeline_step": "IMPORT", "pipeline_progress": 5,
        "permissions_count": 5, "has_sensitive_permissions": False,
        "dependencies": [], "last_accessed": "2026-03-04T07:00:00Z",
        "created_date": "2024-11-20T13:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "ViewAuditLog"],
    },
    {
        "id": "ACC-00009", "name": "dev-kubernetes-admin", "userName": "k8s_dev",
        "address": "dev-k8s.lab.corp.net", "safeName": "DEV-Containers",
        "platformId": "UnixSSH", "secretType": "sshkey",
        "department": "DevOps", "title": "DevOps Engineer", "role": "admin",
        "manager": "Marcus Rivera", "employee_id": "EMP-10317",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 1, "wave_reason": "safe matches 'dev' pattern",
        "batch": "W1B0", "risk": "low", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 10, "has_sensitive_permissions": True,
        "dependencies": [], "last_accessed": "2026-03-05T15:30:00Z",
        "created_date": "2024-07-10T09:00:00Z",
        "target_role_a": "Edit", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "AddAccounts", "UpdateAccountContent", "UpdateAccountProperties", "DeleteAccounts", "ViewAuditLog", "ManageSafe"],
    },
    {
        "id": "ACC-00010", "name": "sandbox-windows-rdp", "userName": "sandbox_rdp",
        "address": "sandbox-win01.lab.corp.net", "safeName": "SANDBOX-Servers",
        "platformId": "WinServerLocal", "secretType": "password",
        "department": "IT Operations", "title": "Help Desk Analyst", "role": "viewer",
        "manager": "David Park", "employee_id": "EMP-10110",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 1, "wave_reason": "safe matches 'sandbox' pattern",
        "batch": "W1B0", "risk": "low", "status": "pending",
        "pipeline_step": "TRANSFORM", "pipeline_progress": 3,
        "permissions_count": 2, "has_sensitive_permissions": False,
        "dependencies": [], "last_accessed": "2026-02-18T08:00:00Z",
        "created_date": "2025-05-01T10:00:00Z",
        "target_role_a": "List", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts"],
    },

    # ── Wave 2: Standard Users (15 accounts) ───────────────────────
    {
        "id": "ACC-00011", "name": "prod-fileserver-01", "userName": "fs_admin",
        "address": "fs01.corp.net", "safeName": "PROD-FileServers",
        "platformId": "WinServerLocal", "secretType": "password",
        "department": "IT Operations", "title": "System Admin", "role": "admin",
        "manager": "David Park", "employee_id": "EMP-10101",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 2, "wave_reason": "standard account — no pattern match, not NHI",
        "batch": "W2B0", "risk": "medium", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 14, "has_sensitive_permissions": True,
        "dependencies": [], "last_accessed": "2026-03-05T09:00:00Z",
        "created_date": "2023-06-01T08:00:00Z",
        "target_role_a": "Owner", "escalation_flag_a": True,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "AddAccounts", "UpdateAccountContent", "UpdateAccountProperties", "DeleteAccounts", "RenameAccounts", "ViewAuditLog", "ManageSafe", "ManageSafeMembers", "InitiateCPMAccountManagementOperations", "AccessWithoutConfirmation"],
    },
    {
        "id": "ACC-00012", "name": "prod-exchange-svc", "userName": "exch_admin",
        "address": "exch01.corp.net", "safeName": "PROD-Exchange",
        "platformId": "WinDomain", "secretType": "password",
        "department": "IT Operations", "title": "System Admin", "role": "admin",
        "manager": "David Park", "employee_id": "EMP-10102",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 2, "wave_reason": "standard account — no pattern match, not NHI",
        "batch": "W2B0", "risk": "medium", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 11, "has_sensitive_permissions": True,
        "dependencies": ["Exchange Server 2019"], "last_accessed": "2026-03-04T14:00:00Z",
        "created_date": "2022-11-15T10:00:00Z",
        "target_role_a": "Edit", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "AddAccounts", "UpdateAccountContent", "UpdateAccountProperties", "DeleteAccounts", "ViewAuditLog", "ManageSafe", "ManageSafeMembers"],
    },
    {
        "id": "ACC-00013", "name": "finance-erp-user", "userName": "erp_finance",
        "address": "erp.corp.net", "safeName": "FIN-ERP",
        "platformId": "WinDomain", "secretType": "password",
        "department": "Finance", "title": "Financial Analyst", "role": "viewer",
        "manager": "Jennifer Walsh", "employee_id": "EMP-20301",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 2, "wave_reason": "standard account — no pattern match, not NHI",
        "batch": "W2B0", "risk": "medium", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 3, "has_sensitive_permissions": False,
        "dependencies": ["SAP ERP"], "last_accessed": "2026-03-03T16:00:00Z",
        "created_date": "2024-01-20T09:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts"],
    },
    {
        "id": "ACC-00014", "name": "hr-payroll-admin", "userName": "payroll_admin",
        "address": "payroll.corp.net", "safeName": "HR-Systems",
        "platformId": "WinDomain", "secretType": "password",
        "department": "HR", "title": "HR Manager", "role": "admin",
        "manager": "Lisa Thompson", "employee_id": "EMP-30101",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 2, "wave_reason": "standard account — no pattern match, not NHI",
        "batch": "W2B0", "risk": "medium", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 8, "has_sensitive_permissions": True,
        "dependencies": ["ADP Payroll"], "last_accessed": "2026-03-05T11:00:00Z",
        "created_date": "2023-04-10T08:00:00Z",
        "target_role_a": "Edit", "escalation_flag_a": True,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "AddAccounts", "UpdateAccountContent", "ViewAuditLog", "AccessWithoutConfirmation"],
    },
    {
        "id": "ACC-00015", "name": "sec-siem-admin", "userName": "siem_admin",
        "address": "siem01.corp.net", "safeName": "SEC-SIEM",
        "platformId": "UnixSSH", "secretType": "password",
        "department": "Security", "title": "Security Analyst", "role": "admin",
        "manager": "Robert Kim", "employee_id": "EMP-40101",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 2, "wave_reason": "standard account — no pattern match, not NHI",
        "batch": "W2B0", "risk": "medium", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 10, "has_sensitive_permissions": True,
        "dependencies": ["Splunk SIEM"], "last_accessed": "2026-03-05T17:00:00Z",
        "created_date": "2023-01-05T08:00:00Z",
        "target_role_a": "Edit", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "AddAccounts", "UpdateAccountContent", "UpdateAccountProperties", "ViewAuditLog", "ManageSafe", "ManageSafeMembers"],
    },
    {
        "id": "ACC-00016", "name": "prod-webserver-01", "userName": "web_admin",
        "address": "web01.corp.net", "safeName": "PROD-WebServers",
        "platformId": "UnixSSH", "secretType": "password",
        "department": "IT Operations", "title": "System Admin", "role": "operator",
        "manager": "David Park", "employee_id": "EMP-10103",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 2, "wave_reason": "standard account — no pattern match, not NHI",
        "batch": "W2B0", "risk": "medium", "status": "in_progress",
        "pipeline_step": "HEARTBEAT", "pipeline_progress": 6,
        "permissions_count": 7, "has_sensitive_permissions": False,
        "dependencies": ["Apache HTTPD"], "last_accessed": "2026-03-04T22:00:00Z",
        "created_date": "2023-08-15T10:00:00Z",
        "target_role_a": "Edit", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "AddAccounts", "UpdateAccountContent", "ViewAuditLog"],
    },
    {
        "id": "ACC-00017", "name": "prod-printserver", "userName": "print_admin",
        "address": "print01.corp.net", "safeName": "PROD-PrintServices",
        "platformId": "WinServerLocal", "secretType": "password",
        "department": "IT Operations", "title": "Help Desk Analyst", "role": "operator",
        "manager": "David Park", "employee_id": "EMP-10111",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 2, "wave_reason": "standard account — no pattern match, not NHI",
        "batch": "W2B0", "risk": "medium", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 4, "has_sensitive_permissions": False,
        "dependencies": [], "last_accessed": "2026-02-28T13:00:00Z",
        "created_date": "2024-04-01T08:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers"],
    },
    {
        "id": "ACC-00018", "name": "finance-treasury-view", "userName": "treasury_ro",
        "address": "treasury.corp.net", "safeName": "FIN-Treasury",
        "platformId": "WinDomain", "secretType": "password",
        "department": "Finance", "title": "Treasury Analyst", "role": "viewer",
        "manager": "Jennifer Walsh", "employee_id": "EMP-20302",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 2, "wave_reason": "standard account — no pattern match, not NHI",
        "batch": "W2B0", "risk": "medium", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 2, "has_sensitive_permissions": False,
        "dependencies": [], "last_accessed": "2026-03-01T10:00:00Z",
        "created_date": "2024-08-01T09:00:00Z",
        "target_role_a": "List", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts"],
    },
    {
        "id": "ACC-00019", "name": "sec-vuln-scanner", "userName": "vuln_admin",
        "address": "vuln01.corp.net", "safeName": "SEC-VulnMgmt",
        "platformId": "UnixSSH", "secretType": "password",
        "department": "Security", "title": "Penetration Tester", "role": "operator",
        "manager": "Robert Kim", "employee_id": "EMP-40102",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 2, "wave_reason": "standard account — no pattern match, not NHI",
        "batch": "W2B0", "risk": "medium", "status": "pending",
        "pipeline_step": "EXPORT", "pipeline_progress": 2,
        "permissions_count": 6, "has_sensitive_permissions": False,
        "dependencies": ["Qualys Scanner"], "last_accessed": "2026-03-03T14:00:00Z",
        "created_date": "2024-02-10T08:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "ViewAuditLog", "UpdateAccountContent"],
    },
    {
        "id": "ACC-00020", "name": "hr-benefits-portal", "userName": "benefits_admin",
        "address": "benefits.corp.net", "safeName": "HR-Benefits",
        "platformId": "WinDomain", "secretType": "password",
        "department": "HR", "title": "Benefits Coordinator", "role": "operator",
        "manager": "Lisa Thompson", "employee_id": "EMP-30102",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 2, "wave_reason": "standard account — no pattern match, not NHI",
        "batch": "W2B0", "risk": "medium", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 5, "has_sensitive_permissions": False,
        "dependencies": [], "last_accessed": "2026-03-02T09:30:00Z",
        "created_date": "2024-05-15T10:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "ViewAuditLog"],
    },
    {
        "id": "ACC-00021", "name": "prod-backup-server", "userName": "backup_admin",
        "address": "backup01.corp.net", "safeName": "PROD-Backup",
        "platformId": "WinServerLocal", "secretType": "password",
        "department": "IT Operations", "title": "Backup Administrator", "role": "operator",
        "manager": "David Park", "employee_id": "EMP-10106",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 2, "wave_reason": "standard account — no pattern match, not NHI",
        "batch": "W2B0", "risk": "medium", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 6, "has_sensitive_permissions": False,
        "dependencies": ["Veeam Backup"], "last_accessed": "2026-03-05T06:00:00Z",
        "created_date": "2023-09-20T08:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "UpdateAccountContent", "ViewAuditLog"],
    },
    {
        "id": "ACC-00022", "name": "devops-ansible-tower", "userName": "ansible_user",
        "address": "ansible01.corp.net", "safeName": "OPS-Automation",
        "platformId": "UnixSSH", "secretType": "sshkey",
        "department": "DevOps", "title": "Automation Engineer", "role": "operator",
        "manager": "Marcus Rivera", "employee_id": "EMP-10318",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 2, "wave_reason": "standard account — no pattern match, not NHI",
        "batch": "W2B0", "risk": "medium", "status": "in_progress",
        "pipeline_step": "CREATE", "pipeline_progress": 4,
        "permissions_count": 8, "has_sensitive_permissions": False,
        "dependencies": ["Ansible Tower"], "last_accessed": "2026-03-05T20:00:00Z",
        "created_date": "2023-11-01T09:00:00Z",
        "target_role_a": "Edit", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "AddAccounts", "UpdateAccountContent", "UpdateAccountProperties", "ViewAuditLog"],
    },
    {
        "id": "ACC-00023", "name": "eng-gitlab-admin", "userName": "gitlab_admin",
        "address": "gitlab.corp.net", "safeName": "ENG-SourceControl",
        "platformId": "UnixSSH", "secretType": "password",
        "department": "Engineering", "title": "Software Engineer", "role": "admin",
        "manager": "Sarah Chen", "employee_id": "EMP-10235",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 2, "wave_reason": "standard account — no pattern match, not NHI",
        "batch": "W2B0", "risk": "medium", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 9, "has_sensitive_permissions": True,
        "dependencies": ["GitLab"], "last_accessed": "2026-03-05T23:00:00Z",
        "created_date": "2023-03-01T08:00:00Z",
        "target_role_a": "Edit", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "AddAccounts", "UpdateAccountContent", "UpdateAccountProperties", "ViewAuditLog", "ManageSafe"],
    },
    {
        "id": "ACC-00024", "name": "finance-audit-ro", "userName": "audit_finance",
        "address": "audit.corp.net", "safeName": "FIN-Audit",
        "platformId": "WinDomain", "secretType": "password",
        "department": "Finance", "title": "Internal Auditor", "role": "viewer",
        "manager": "Jennifer Walsh", "employee_id": "EMP-20303",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 2, "wave_reason": "standard account — no pattern match, not NHI",
        "batch": "W2B0", "risk": "medium", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 3, "has_sensitive_permissions": False,
        "dependencies": [], "last_accessed": "2026-03-04T15:00:00Z",
        "created_date": "2024-03-01T09:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "ViewAuditLog", "ViewSafeMembers"],
    },
    {
        "id": "ACC-00025", "name": "prod-dns-primary", "userName": "dns_admin",
        "address": "dns01.corp.net", "safeName": "PROD-DNS",
        "platformId": "WinServerLocal", "secretType": "password",
        "department": "IT Operations", "title": "Network Engineer", "role": "operator",
        "manager": "David Park", "employee_id": "EMP-10107",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 2, "wave_reason": "standard account — no pattern match, not NHI",
        "batch": "W2B0", "risk": "medium", "status": "blocked",
        "pipeline_step": "FREEZE", "pipeline_progress": 1,
        "permissions_count": 6, "has_sensitive_permissions": False,
        "dependencies": ["Active Directory DNS"], "last_accessed": "2026-03-05T12:00:00Z",
        "created_date": "2023-02-01T08:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "UpdateAccountContent", "ViewAuditLog"],
    },

    # ── Wave 3: Infrastructure (10 accounts) ───────────────────────
    {
        "id": "ACC-00026", "name": "infra-core-switch-01", "userName": "switch_admin",
        "address": "core-sw01.corp.net", "safeName": "INFRA-NetworkDevices",
        "platformId": "UnixSSH", "secretType": "password",
        "department": "IT Operations", "title": "Network Engineer", "role": "admin",
        "manager": "David Park", "employee_id": "EMP-10108",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 3, "wave_reason": "safe matches 'infra' pattern + name matches 'switch'",
        "batch": "W3B0", "risk": "high", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 12, "has_sensitive_permissions": True,
        "dependencies": ["Cisco ISE"], "last_accessed": "2026-03-05T08:00:00Z",
        "created_date": "2022-06-01T08:00:00Z",
        "target_role_a": "Owner", "escalation_flag_a": True,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "AddAccounts", "UpdateAccountContent", "UpdateAccountProperties", "DeleteAccounts", "ViewAuditLog", "ManageSafe", "ManageSafeMembers", "InitiateCPMAccountManagementOperations"],
    },
    {
        "id": "ACC-00027", "name": "infra-firewall-palo", "userName": "fw_admin",
        "address": "fw01.corp.net", "safeName": "INFRA-Firewalls",
        "platformId": "UnixSSH", "secretType": "password",
        "department": "Security", "title": "Security Engineer", "role": "admin",
        "manager": "Robert Kim", "employee_id": "EMP-40103",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 3, "wave_reason": "safe matches 'infra' pattern + name matches 'firewall'",
        "batch": "W3B0", "risk": "high", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 10, "has_sensitive_permissions": True,
        "dependencies": ["Panorama"], "last_accessed": "2026-03-05T19:00:00Z",
        "created_date": "2022-04-15T08:00:00Z",
        "target_role_a": "Edit", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "AddAccounts", "UpdateAccountContent", "UpdateAccountProperties", "ViewAuditLog", "ManageSafe", "ManageSafeMembers"],
    },
    {
        "id": "ACC-00028", "name": "network-router-core", "userName": "router_admin",
        "address": "rtr01.corp.net", "safeName": "INFRA-Routers",
        "platformId": "UnixSSH", "secretType": "password",
        "department": "IT Operations", "title": "Network Engineer", "role": "admin",
        "manager": "David Park", "employee_id": "EMP-10109",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 3, "wave_reason": "name matches 'router' pattern",
        "batch": "W3B0", "risk": "high", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 9, "has_sensitive_permissions": True,
        "dependencies": ["Cisco DNA Center"], "last_accessed": "2026-03-04T07:30:00Z",
        "created_date": "2022-08-01T08:00:00Z",
        "target_role_a": "Edit", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "AddAccounts", "UpdateAccountContent", "UpdateAccountProperties", "ViewAuditLog", "ManageSafe"],
    },
    {
        "id": "ACC-00029", "name": "admin-domain-controller", "userName": "dc_admin",
        "address": "dc01.corp.net", "safeName": "ADMIN-DomainControllers",
        "platformId": "WinDomain", "secretType": "password",
        "department": "IT Operations", "title": "Senior System Admin", "role": "admin",
        "manager": "David Park", "employee_id": "EMP-10104",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 3, "wave_reason": "safe matches 'admin' pattern",
        "batch": "W3B0", "risk": "high", "status": "in_progress",
        "pipeline_step": "IMPORT", "pipeline_progress": 5,
        "permissions_count": 18, "has_sensitive_permissions": True,
        "dependencies": ["Active Directory", "Group Policy"], "last_accessed": "2026-03-05T23:59:00Z",
        "created_date": "2021-01-15T08:00:00Z",
        "target_role_a": "Owner", "escalation_flag_a": True,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "AddAccounts", "UpdateAccountContent", "UpdateAccountProperties", "DeleteAccounts", "RenameAccounts", "UnlockAccounts", "ViewAuditLog", "ManageSafe", "ManageSafeMembers", "InitiateCPMAccountManagementOperations", "AccessWithoutConfirmation", "SpecifyNextAccountContent", "BackupSafe", "CreateFolders"],
    },
    {
        "id": "ACC-00030", "name": "infra-vcenter-admin", "userName": "vcenter_admin",
        "address": "vcenter.corp.net", "safeName": "INFRA-VMware",
        "platformId": "WinDomain", "secretType": "password",
        "department": "IT Operations", "title": "Virtualization Admin", "role": "admin",
        "manager": "David Park", "employee_id": "EMP-10112",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 3, "wave_reason": "safe matches 'infra' pattern",
        "batch": "W3B0", "risk": "high", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 14, "has_sensitive_permissions": True,
        "dependencies": ["VMware vCenter", "vSphere"], "last_accessed": "2026-03-05T16:00:00Z",
        "created_date": "2022-03-01T08:00:00Z",
        "target_role_a": "Owner", "escalation_flag_a": True,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "AddAccounts", "UpdateAccountContent", "UpdateAccountProperties", "DeleteAccounts", "ViewAuditLog", "ManageSafe", "ManageSafeMembers", "InitiateCPMAccountManagementOperations", "AccessWithoutConfirmation", "RenameAccounts"],
    },
    {
        "id": "ACC-00031", "name": "infra-loadbalancer-f5", "userName": "f5_admin",
        "address": "f5-lb01.corp.net", "safeName": "INFRA-LoadBalancers",
        "platformId": "UnixSSH", "secretType": "password",
        "department": "IT Operations", "title": "Network Engineer", "role": "operator",
        "manager": "David Park", "employee_id": "EMP-10113",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 3, "wave_reason": "safe matches 'infra' pattern",
        "batch": "W3B0", "risk": "high", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 8, "has_sensitive_permissions": False,
        "dependencies": ["F5 BIG-IP"], "last_accessed": "2026-03-03T11:00:00Z",
        "created_date": "2023-05-01T08:00:00Z",
        "target_role_a": "Edit", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "AddAccounts", "UpdateAccountContent", "UpdateAccountProperties", "ViewAuditLog"],
    },
    {
        "id": "ACC-00032", "name": "admin-hyperv-cluster", "userName": "hyperv_admin",
        "address": "hyperv01.corp.net", "safeName": "ADMIN-HyperV",
        "platformId": "WinServerLocal", "secretType": "password",
        "department": "IT Operations", "title": "System Admin", "role": "admin",
        "manager": "David Park", "employee_id": "EMP-10114",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 3, "wave_reason": "safe matches 'admin' pattern",
        "batch": "W3B0", "risk": "high", "status": "pending",
        "pipeline_step": "TRANSFORM", "pipeline_progress": 3,
        "permissions_count": 11, "has_sensitive_permissions": True,
        "dependencies": ["Hyper-V Cluster"], "last_accessed": "2026-03-04T14:30:00Z",
        "created_date": "2022-12-01T08:00:00Z",
        "target_role_a": "Edit", "escalation_flag_a": True,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "AddAccounts", "UpdateAccountContent", "UpdateAccountProperties", "DeleteAccounts", "ViewAuditLog", "ManageSafe", "ManageSafeMembers"],
    },
    {
        "id": "ACC-00033", "name": "infra-storage-netapp", "userName": "netapp_admin",
        "address": "netapp01.corp.net", "safeName": "INFRA-Storage",
        "platformId": "UnixSSH", "secretType": "password",
        "department": "IT Operations", "title": "Storage Admin", "role": "operator",
        "manager": "David Park", "employee_id": "EMP-10115",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 3, "wave_reason": "safe matches 'infra' pattern",
        "batch": "W3B0", "risk": "high", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 7, "has_sensitive_permissions": False,
        "dependencies": ["NetApp ONTAP"], "last_accessed": "2026-03-02T06:00:00Z",
        "created_date": "2023-07-01T08:00:00Z",
        "target_role_a": "Edit", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "AddAccounts", "UpdateAccountContent", "ViewAuditLog"],
    },
    {
        "id": "ACC-00034", "name": "admin-wsus-server", "userName": "wsus_admin",
        "address": "wsus01.corp.net", "safeName": "ADMIN-Patching",
        "platformId": "WinServerLocal", "secretType": "password",
        "department": "IT Operations", "title": "System Admin", "role": "operator",
        "manager": "David Park", "employee_id": "EMP-10116",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 3, "wave_reason": "safe matches 'admin' pattern",
        "batch": "W3B0", "risk": "high", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 6, "has_sensitive_permissions": False,
        "dependencies": ["WSUS"], "last_accessed": "2026-02-28T10:00:00Z",
        "created_date": "2024-01-15T08:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "UpdateAccountContent", "ViewAuditLog"],
    },
    {
        "id": "ACC-00035", "name": "network-wifi-controller", "userName": "wifi_admin",
        "address": "wlc01.corp.net", "safeName": "INFRA-Wireless",
        "platformId": "UnixSSH", "secretType": "password",
        "department": "IT Operations", "title": "Network Engineer", "role": "operator",
        "manager": "David Park", "employee_id": "EMP-10117",
        "is_nhi": False, "nhi_type": None, "nhi_confidence": 0.0,
        "nhi_signals": [],
        "wave": 3, "wave_reason": "safe matches 'infra' pattern + name matches 'network'",
        "batch": "W3B0", "risk": "high", "status": "blocked",
        "pipeline_step": "FREEZE", "pipeline_progress": 1,
        "permissions_count": 5, "has_sensitive_permissions": False,
        "dependencies": ["Cisco WLC", "Cisco ISE"], "last_accessed": "2026-03-01T14:00:00Z",
        "created_date": "2023-10-01T08:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "ViewAuditLog"],
    },

    # ── Wave 4: NHI without CCP/AAM (8 accounts) ──────────────────
    {
        "id": "ACC-00036", "name": "svc-backup-agent", "userName": "svc-backup",
        "address": "backup-svc.corp.net", "safeName": "SVC-BackupAgents",
        "platformId": "WinServiceAccount", "secretType": "password",
        "department": "IT Operations", "title": "Service Account", "role": "service",
        "manager": "David Park", "employee_id": "EMP-SVC-001",
        "is_nhi": True, "nhi_type": "service_account", "nhi_confidence": 0.95,
        "nhi_signals": ["platform:WinServiceAccount", "name_pattern:^svc-", "container:SVC-"],
        "wave": 4, "wave_reason": "NHI detected (service_account, confidence 0.95) — no CCP/AAM integration",
        "batch": "W4B0", "risk": "high", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 4, "has_sensitive_permissions": False,
        "dependencies": ["Veeam Agent"], "last_accessed": "2026-03-05T04:00:00Z",
        "created_date": "2022-05-01T08:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers"],
    },
    {
        "id": "ACC-00037", "name": "svc-monitoring-nagios", "userName": "svc-nagios",
        "address": "nagios01.corp.net", "safeName": "SVC-Monitoring",
        "platformId": "UnixSSH", "secretType": "password",
        "department": "IT Operations", "title": "Service Account", "role": "service",
        "manager": "David Park", "employee_id": "EMP-SVC-002",
        "is_nhi": True, "nhi_type": "service_account", "nhi_confidence": 0.92,
        "nhi_signals": ["platform:UnixSSH", "name_pattern:^svc-", "container:SVC-"],
        "wave": 4, "wave_reason": "NHI detected (service_account, confidence 0.92) — no CCP/AAM integration",
        "batch": "W4B0", "risk": "high", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 3, "has_sensitive_permissions": False,
        "dependencies": ["Nagios XI"], "last_accessed": "2026-03-05T05:00:00Z",
        "created_date": "2022-09-01T08:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts"],
    },
    {
        "id": "ACC-00038", "name": "app-etl-pipeline", "userName": "app-etl",
        "address": "etl01.corp.net", "safeName": "APP-DataPipeline",
        "platformId": "WinServiceAccount", "secretType": "password",
        "department": "Engineering", "title": "Application Identity", "role": "service",
        "manager": "Sarah Chen", "employee_id": "EMP-SVC-003",
        "is_nhi": True, "nhi_type": "application_identity", "nhi_confidence": 0.88,
        "nhi_signals": ["name_pattern:^app-", "container:APP-"],
        "wave": 4, "wave_reason": "NHI detected (application_identity, confidence 0.88) — no CCP/AAM integration",
        "batch": "W4B0", "risk": "high", "status": "in_progress",
        "pipeline_step": "HEARTBEAT", "pipeline_progress": 6,
        "permissions_count": 5, "has_sensitive_permissions": False,
        "dependencies": ["Informatica ETL"], "last_accessed": "2026-03-05T03:00:00Z",
        "created_date": "2023-02-15T08:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "ViewAuditLog"],
    },
    {
        "id": "ACC-00039", "name": "db-replication-user", "userName": "db_repl",
        "address": "db-cluster.corp.net", "safeName": "DB-Replication",
        "platformId": "Oracle", "secretType": "password",
        "department": "Engineering", "title": "Database Account", "role": "service",
        "manager": "Sarah Chen", "employee_id": "EMP-SVC-004",
        "is_nhi": True, "nhi_type": "database_account", "nhi_confidence": 0.91,
        "nhi_signals": ["platform:Oracle", "name_pattern:db-", "container:DB-"],
        "wave": 4, "wave_reason": "NHI detected (database_account, confidence 0.91) — no CCP/AAM integration",
        "batch": "W4B0", "risk": "high", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 3, "has_sensitive_permissions": False,
        "dependencies": ["Oracle Data Guard"], "last_accessed": "2026-03-05T02:00:00Z",
        "created_date": "2022-07-01T08:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts"],
    },
    {
        "id": "ACC-00040", "name": "svc-scan-qualys", "userName": "svc-qualys",
        "address": "qualys-scan.corp.net", "safeName": "SVC-SecurityScanning",
        "platformId": "WinServiceAccount", "secretType": "password",
        "department": "Security", "title": "Service Account", "role": "service",
        "manager": "Robert Kim", "employee_id": "EMP-SVC-005",
        "is_nhi": True, "nhi_type": "service_account", "nhi_confidence": 0.93,
        "nhi_signals": ["platform:WinServiceAccount", "name_pattern:^svc-", "container:SVC-"],
        "wave": 4, "wave_reason": "NHI detected (service_account, confidence 0.93) — no CCP/AAM integration",
        "batch": "W4B0", "risk": "high", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 4, "has_sensitive_permissions": False,
        "dependencies": ["Qualys Cloud"], "last_accessed": "2026-03-04T06:00:00Z",
        "created_date": "2023-04-01T08:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers"],
    },
    {
        "id": "ACC-00041", "name": "rpa-finance-bot", "userName": "rpa_fin_bot",
        "address": "rpa01.corp.net", "safeName": "RPA-FinanceAutomation",
        "platformId": "WinDomain", "secretType": "password",
        "department": "Finance", "title": "Robotic Process", "role": "service",
        "manager": "Jennifer Walsh", "employee_id": "EMP-SVC-006",
        "is_nhi": True, "nhi_type": "robotic_process", "nhi_confidence": 0.87,
        "nhi_signals": ["name_pattern:rpa", "container:RPA-"],
        "wave": 4, "wave_reason": "NHI detected (robotic_process, confidence 0.87) — no CCP/AAM integration",
        "batch": "W4B0", "risk": "high", "status": "pending",
        "pipeline_step": "EXPORT", "pipeline_progress": 2,
        "permissions_count": 6, "has_sensitive_permissions": False,
        "dependencies": ["UiPath", "SAP ERP"], "last_accessed": "2026-03-05T01:00:00Z",
        "created_date": "2024-06-01T08:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "UpdateAccountContent", "ViewAuditLog"],
    },
    {
        "id": "ACC-00042", "name": "shared-vendor-access", "userName": "vendor_shared",
        "address": "vendor-portal.corp.net", "safeName": "SHARED-VendorAccess",
        "platformId": "WinDomain", "secretType": "password",
        "department": "IT Operations", "title": "Shared Account", "role": "service",
        "manager": "David Park", "employee_id": "EMP-SVC-007",
        "is_nhi": True, "nhi_type": "shared_account", "nhi_confidence": 0.78,
        "nhi_signals": ["name_pattern:shared", "container:SHARED-"],
        "wave": 4, "wave_reason": "NHI detected (shared_account, confidence 0.78) — no CCP/AAM integration",
        "batch": "W4B0", "risk": "high", "status": "blocked",
        "pipeline_step": "FREEZE", "pipeline_progress": 1,
        "permissions_count": 8, "has_sensitive_permissions": True,
        "dependencies": ["Vendor VPN", "ServiceNow"], "last_accessed": "2026-03-03T09:00:00Z",
        "created_date": "2023-11-15T08:00:00Z",
        "target_role_a": "Edit", "escalation_flag_a": True,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "UpdateAccountContent", "UpdateAccountProperties", "ViewAuditLog", "AccessWithoutConfirmation"],
    },
    {
        "id": "ACC-00043", "name": "machine-id-cert-mgr", "userName": "cert_machine",
        "address": "pki01.corp.net", "safeName": "PKI-CertManagement",
        "platformId": "WinServiceAccount", "secretType": "password",
        "department": "Security", "title": "Machine Identity", "role": "service",
        "manager": "Robert Kim", "employee_id": "EMP-SVC-008",
        "is_nhi": True, "nhi_type": "machine_identity", "nhi_confidence": 0.85,
        "nhi_signals": ["platform:WinServiceAccount", "name_pattern:machine"],
        "wave": 4, "wave_reason": "NHI detected (machine_identity, confidence 0.85) — no CCP/AAM integration",
        "batch": "W4B0", "risk": "high", "status": "migrated",
        "pipeline_step": "COMPLETE", "pipeline_progress": 7,
        "permissions_count": 5, "has_sensitive_permissions": False,
        "dependencies": ["Microsoft PKI"], "last_accessed": "2026-03-04T22:00:00Z",
        "created_date": "2023-06-01T08:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "ViewAuditLog"],
    },

    # ── Wave 5: NHI with CCP/AAM (7 accounts) ─────────────────────
    {
        "id": "ACC-00044", "name": "svc-jenkins-deploy", "userName": "svc-jenkins",
        "address": "jenkins.corp.net", "safeName": "CICD-Pipeline",
        "platformId": "WinServiceAccount", "secretType": "password",
        "department": "DevOps", "title": "Service Account", "role": "service",
        "manager": "Marcus Rivera", "employee_id": "EMP-SVC-009",
        "is_nhi": True, "nhi_type": "service_account", "nhi_confidence": 0.97,
        "nhi_signals": ["platform:WinServiceAccount", "name_pattern:^svc-", "container:CICD-"],
        "wave": 5, "wave_reason": "NHI detected (confidence 0.97) + CCP/AAM integration found (Jenkins CCP plugin)",
        "batch": "W5B0", "risk": "critical", "status": "in_progress",
        "pipeline_step": "TRANSFORM", "pipeline_progress": 3,
        "permissions_count": 6, "has_sensitive_permissions": False,
        "dependencies": ["Jenkins", "CCP Plugin", "Artifactory"], "last_accessed": "2026-03-05T23:59:00Z",
        "created_date": "2022-01-15T08:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "UpdateAccountContent", "ViewAuditLog"],
    },
    {
        "id": "ACC-00045", "name": "app-payment-gateway", "userName": "app-payment",
        "address": "payment-gw.corp.net", "safeName": "APP-PaymentProcessing",
        "platformId": "WinServiceAccount", "secretType": "password",
        "department": "Finance", "title": "Application Identity", "role": "service",
        "manager": "Jennifer Walsh", "employee_id": "EMP-SVC-010",
        "is_nhi": True, "nhi_type": "application_identity", "nhi_confidence": 0.96,
        "nhi_signals": ["name_pattern:^app-", "container:APP-", "platform:WinServiceAccount"],
        "wave": 5, "wave_reason": "NHI detected (confidence 0.96) + AAM integration found (payment app credential provider)",
        "batch": "W5B0", "risk": "critical", "status": "pending",
        "pipeline_step": "FREEZE", "pipeline_progress": 1,
        "permissions_count": 5, "has_sensitive_permissions": False,
        "dependencies": ["Payment Gateway", "AAM CP", "PCI Zone Firewall"], "last_accessed": "2026-03-05T23:58:00Z",
        "created_date": "2021-06-01T08:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "ViewAuditLog"],
    },
    {
        "id": "ACC-00046", "name": "svc-terraform-cloud", "userName": "svc-terraform",
        "address": "terraform.corp.net", "safeName": "CICD-IaC",
        "platformId": "AWSAccessKeys", "secretType": "aws_access_key",
        "department": "DevOps", "title": "Service Account", "role": "service",
        "manager": "Marcus Rivera", "employee_id": "EMP-SVC-011",
        "is_nhi": True, "nhi_type": "api_key", "nhi_confidence": 0.94,
        "nhi_signals": ["platform:AWSAccessKeys", "name_pattern:^svc-", "container:CICD-"],
        "wave": 5, "wave_reason": "NHI detected (api_key, confidence 0.94) + CCP integration found (Terraform CCP module)",
        "batch": "W5B0", "risk": "critical", "status": "pending",
        "pipeline_step": "FREEZE", "pipeline_progress": 1,
        "permissions_count": 4, "has_sensitive_permissions": False,
        "dependencies": ["Terraform Cloud", "AWS IAM", "CCP REST"], "last_accessed": "2026-03-05T22:00:00Z",
        "created_date": "2023-01-01T08:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers"],
    },
    {
        "id": "ACC-00047", "name": "app-crm-integration", "userName": "app-crm",
        "address": "crm-api.corp.net", "safeName": "APP-CRM",
        "platformId": "WinServiceAccount", "secretType": "password",
        "department": "Engineering", "title": "Application Identity", "role": "service",
        "manager": "Sarah Chen", "employee_id": "EMP-SVC-012",
        "is_nhi": True, "nhi_type": "application_identity", "nhi_confidence": 0.90,
        "nhi_signals": ["name_pattern:^app-", "container:APP-", "platform:WinServiceAccount"],
        "wave": 5, "wave_reason": "NHI detected (confidence 0.90) + AAM integration found (CRM credential provider)",
        "batch": "W5B0", "risk": "critical", "status": "pending",
        "pipeline_step": "FREEZE", "pipeline_progress": 1,
        "permissions_count": 4, "has_sensitive_permissions": False,
        "dependencies": ["Salesforce API", "AAM CP"], "last_accessed": "2026-03-04T18:00:00Z",
        "created_date": "2023-08-01T08:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers"],
    },
    {
        "id": "ACC-00048", "name": "svc-azure-devops", "userName": "svc-azdo",
        "address": "dev.azure.com", "safeName": "CICD-AzureDevOps",
        "platformId": "AzureServicePrincipal", "secretType": "client_secret",
        "department": "DevOps", "title": "Service Account", "role": "service",
        "manager": "Marcus Rivera", "employee_id": "EMP-SVC-013",
        "is_nhi": True, "nhi_type": "api_key", "nhi_confidence": 0.96,
        "nhi_signals": ["platform:AzureServicePrincipal", "name_pattern:^svc-", "container:CICD-"],
        "wave": 5, "wave_reason": "NHI detected (api_key, confidence 0.96) + CCP integration found (AzDO pipeline CCP task)",
        "batch": "W5B0", "risk": "critical", "status": "pending",
        "pipeline_step": "FREEZE", "pipeline_progress": 1,
        "permissions_count": 3, "has_sensitive_permissions": False,
        "dependencies": ["Azure DevOps", "Azure AD", "CCP REST"], "last_accessed": "2026-03-05T21:00:00Z",
        "created_date": "2023-03-15T08:00:00Z",
        "target_role_a": "List", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts"],
    },
    {
        "id": "ACC-00049", "name": "svc-ansible-tower-prod", "userName": "svc-ansible-prod",
        "address": "ansible-prod.corp.net", "safeName": "CICD-Automation",
        "platformId": "UnixSSHKeys", "secretType": "sshkey",
        "department": "DevOps", "title": "Service Account", "role": "service",
        "manager": "Marcus Rivera", "employee_id": "EMP-SVC-014",
        "is_nhi": True, "nhi_type": "service_account", "nhi_confidence": 0.94,
        "nhi_signals": ["platform:UnixSSHKeys", "name_pattern:^svc-", "container:CICD-"],
        "wave": 5, "wave_reason": "NHI detected (confidence 0.94) + CCP integration found (Ansible lookup plugin)",
        "batch": "W5B0", "risk": "critical", "status": "blocked",
        "pipeline_step": "FREEZE", "pipeline_progress": 1,
        "permissions_count": 5, "has_sensitive_permissions": False,
        "dependencies": ["Ansible Tower", "CCP REST", "SSH Key Rotation"], "last_accessed": "2026-03-05T20:00:00Z",
        "created_date": "2022-11-01T08:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers", "ViewAuditLog"],
    },
    {
        "id": "ACC-00050", "name": "app-data-warehouse", "userName": "app-dwh",
        "address": "dwh.corp.net", "safeName": "APP-DataWarehouse",
        "platformId": "MSSql", "secretType": "password",
        "department": "Engineering", "title": "Application Identity", "role": "service",
        "manager": "Sarah Chen", "employee_id": "EMP-SVC-015",
        "is_nhi": True, "nhi_type": "database_account", "nhi_confidence": 0.89,
        "nhi_signals": ["platform:MSSql", "name_pattern:^app-", "container:APP-"],
        "wave": 5, "wave_reason": "NHI detected (database_account, confidence 0.89) + AAM integration found (DWH credential provider)",
        "batch": "W5B0", "risk": "critical", "status": "pending",
        "pipeline_step": "FREEZE", "pipeline_progress": 1,
        "permissions_count": 4, "has_sensitive_permissions": False,
        "dependencies": ["SQL Server DWH", "AAM CP", "SSIS Packages"], "last_accessed": "2026-03-05T04:00:00Z",
        "created_date": "2022-04-01T08:00:00Z",
        "target_role_a": "View", "escalation_flag_a": False,
        "target_permissions_b": ["ListAccounts", "UseAccounts", "RetrieveAccounts", "ViewSafeMembers"],
    },
]


# ── Wave metadata for migration flow ────────────────────────────────
WAVE_META = {
    1: {
        "name": "Test/Dev",
        "risk": "low",
        "classification_rules": ["name matches: test|dev|sandbox|poc|lab|demo"],
        "gate": "g7",
    },
    2: {
        "name": "Standard",
        "risk": "medium",
        "classification_rules": ["no pattern match AND not NHI — default bucket"],
        "gate": "g8",
    },
    3: {
        "name": "Infrastructure",
        "risk": "high",
        "classification_rules": ["name/safe matches: infra|network|firewall|switch|router|admin"],
        "gate": "g9",
    },
    4: {
        "name": "NHI (No CCP/AAM)",
        "risk": "high",
        "classification_rules": ["Agent 12 NHI detected (confidence >= 0.70)", "no CCP/AAM integration in Applications API"],
        "gate": "g10",
    },
    5: {
        "name": "NHI (CCP/AAM)",
        "risk": "critical",
        "classification_rules": ["Agent 12 NHI detected (confidence >= 0.70)", "CCP/AAM integration found via Applications API"],
        "gate": "g11",
    },
}

ETL_STEPS = ["FREEZE", "EXPORT", "TRANSFORM", "CREATE", "IMPORT", "HEARTBEAT", "UNFREEZE"]
